Repository zarusz/SlimMessageBus, pull requests merged in 2024-06, with the labels that each got.

#263 [Host.Outbox] Ensure SQL tables are provisioned and baseline test
  infrastructure.ps1
  src/Host.Plugin.Properties.xml
  src/Infrastructure/README.md
  src/SlimMessageBus.Host.AzureServiceBus/ServiceBusMessageBus.cs
  src/SlimMessageBus.Host.Interceptor/Bus/MessageBusLifecycleEventType.cs
  src/SlimMessageBus.Host.Outbox/Interceptors/OutboxSendingTask.cs
  src/SlimMessageBus.Host/MessageBusBase.cs
  src/SlimMessageBus.sln
  src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusIt.cs
  src/Tests/SlimMessageBus.Host.AzureServiceBus.Test/ServiceBusMessageBusTests.cs
  src/Tests/SlimMessageBus.Host.Integration.Test/HybridTests.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/BusType.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/DatabaseFacadeExtenstions.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxBenchmarkTests.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/OutboxTests.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/TransactionType.cs
  src/Tests/SlimMessageBus.Host.Outbox.DbContext.Test/Usings.cs
  src/Tests/SlimMessageBus.Host.Test.Common/IntegrationTest/BaseIntegrationTest.cs
  src/Tests/SlimMessageBus.Host.Test.Common/MoqExtensions.cs
  src/Tests/SlimMessageBus.Host.Test/Consumer/ConsumerInstanceMessageProcessorTest.cs
  src/Tests/SlimMessageBus.Host.Test/GlobalUsings.cs
  src/Tests/SlimMessageBus.Host.Test/Hybrid/HybridMessageBusTest.cs
  src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs
  src/Tests/SlimMessageBus.Host.Test/MessageBusTested.cs
  src/Tests/SlimMessageBus.Host.Test/SampleMessages.cs
  src/secrets.txt.sample
Labels: enhancement, Host.Outbox

#264 [DevOps] Add SourceLink support
  .github/workflows/build.yml
  README.md
  build/do_push_prod.ps1
  build/tasks.ps1
  docs/intro.md
  docs/intro.t.md
  docs/plugin_outbox.md
  src/Common.NuGet.Properties.xml
  src/Host.Plugin.Properties.xml
  src/SlimMessageBus.Host.Configuration/SlimMessageBus.Host.Configuration.csproj
  src/SlimMessageBus.Host.Interceptor/SlimMessageBus.Host.Interceptor.csproj
  src/SlimMessageBus.Host.Serialization/SlimMessageBus.Host.Serialization.csproj
  src/SlimMessageBus.sln
  src/SlimMessageBus/SlimMessageBus.csproj
Labels: enhancement, Core

#272 #271 Allow for publishing of messages to a request/response queue. D…
  src/SlimMessageBus.Host/MessageBusBase.cs
  src/Tests/SlimMessageBus.Host.Test/MessageBusBaseTests.cs
Labels: enhancement
